### ISSUE TITLE
XDV.1.9 subbranch with S:A435S(8 sequences, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#1973] opened 2024-09-01 11:26 UTC
XDV.1.9> G4255A> G4300T, G22865T(S:A435S)
Query: G4255A, G4300T, G22865T

Earliest sequence: 06-03 Heilongjiang, China EPI_ISL_19211893
Latest sequence: 08-14 Taiwan, China (Imported) EPI_ISL_19369220
Regions detected: China 5(Including 1 imported reported by Taiwan), Japan 1, New Zealand 1, Korea 1

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4c63a_44db30.json?c=country&label=id:node_7161850
![image](https://github.com/user-attachments/assets/47210635-73bd-4ce5-b52a-52384777da12)

Sequences:
EPI_ISL_19211893, EPI_ISL_19272090, EPI_ISL_19314988,
EPI_ISL_19315042, EPI_ISL_19362962, EPI_ISL_19369104,
EPI_ISL_19369220, EPI_ISL_19371569

**Comment by aviczhl2** [comment] 2024-09-01 11:53
Duplicate of #1956

**Closed by aviczhl2** 2024-09-01 11:53 UTC
