### ISSUE TITLE
Mini saltation JN.1.4 with S:N30K, V47I, R346T and Orf9b:L64P, (4,  Hong Kong)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2204] opened 2024-11-06 13:48 UTC
JN.1.4 >> ORF1a :A4285V (C13119T) > ORF1a:P1786L (C5622T=PLPRO_P223L) > C5365T > 
ORF1a:A2529V (C7851T), T10636C, ORF1b:L137F (C13876T), S:N30K (T21652A),S:V47I (G21701A),S:R346T (G22599C)  ORF9b:L64P (T28474C)  

Query : C5365T,C7851T, T10636C
Samples: 4 all from Hong Kong
First collected on September 20

Tree:
<img width="1160" alt="Screenshot 2024-11-06 alle 14 47 52" src="https://github.com/user-attachments/assets/ae87ea41-5bc7-4ccb-a813-3b3ee14fe13b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice6_genome_test_830a_b50ad0.json?label=id:node_7102718

**Comment by xz-keg** [comment] 2024-11-10 23:42
just realized this is a duplicate of #2178.

**Comment by FedeGueli** [comment] 2024-11-10 23:46
> just realized this is a duplicate of #2178.

Same here! added the query from it in the issue by @ryhisner

**Closed** 2024-11-10 23:46 UTC
Labels: S:346, ORF9b, duplicate, S:30, JN.1.4, S:47
