### ISSUE TITLE
XBB.1.9.2 mini saltation with ORF1b:P1001S, ORF1b:P1821S, S:R214H, ORF3a:P240L, ORF7b:H42Y (13 seqs, mainly in Belgium, USA)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#72] opened 2023-05-19 12:43 UTC
**Defining mutations:** _(On XBB.1.9.2 Polytomy)_ > G405A_rev (ORF1a:R47K_rev) > T10029C_rev (ORF1a:I3255T_rev), C18928T (ORF1b:P1821S) > C16468T (ORF1b:P1001S), G22203A (S:R214H), C26111T (ORF3a:P240L), C27879T (ORF7b:H42Y) >
**Query:** C16468T, C18928T, C26111T
**Earliest seq:** 2023-04-24 (EPI_ISL_17664706)
**Latest seq:** 2023-05-06 (EPI_ISL_17692424)
<details><summary>Genomes: </summary>
EPI_ISL_17664705, EPI_ISL_17664706, EPI_ISL_17664707, EPI_ISL_17664711, EPI_ISL_17664712, EPI_ISL_17664715, EPI_ISL_17664725, EPI_ISL_17664726, EPI_ISL_17664729, EPI_ISL_17664730, EPI_ISL_17692424
</details>

not sure if G405A_Reversion (ORF1a:R47K_Reversion) and T9866C_Reversion (ORF1a:F3201L_Reversion) are real. A405G is one of those defines BJ.1 and donates to XBB, same goes C9866T from BA.2.75 to XBB. Both seems on NNNs. S gene looks good though.

![213+214](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/a7ee33c5-dd00-4a66-8a33-5c6094f21395)

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_34bff_1644e0.json?f_userOrOld=uploaded%20sample

![XBB 1 9 2 mini saltation with S_R214H, S_G257D](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c2db9351-08d5-49a8-8158-d3fcde9750ed)

**Comment by FedeGueli** [comment] 2023-05-30 22:18
6 seqs. @JosetteSchoenma could you check if this is recombinant of some sort please?

**Comment by JosetteSchoenma** [comment] 2023-05-31 19:38
I cannot find anything it would have recombined with. I do think it are 11 sequences though.
The others might have been missed because the sequences are so bad.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/cf924cc1-b711-461b-ae40-2c6cc4796468)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/1c46467e-e878-4828-b594-1f1f6da35575)

Query: C16468T, C18928T, C26111T

**Comment by JosetteSchoenma** [comment] 2023-05-31 20:01
Wait, actually those extra ones only have S:R214H, not S:G257D. But with very bad sequences with N;s so close, you never now.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/96a455f7-322d-4381-9e31-761024ed74a9)

I would just wait for them to show up in other countries, or from Belgium but sequenced by other labs.

**Comment by FedeGueli** [comment] 2023-05-31 20:16
Thank you @JosetteSchoenma !

**Comment by JosetteSchoenma** [comment] 2023-06-13 06:18
Since the US sample does not have any N's and Nextclade calls it XBB.1.9.2 with solely private mutations, my assessment that this is not a recombinant has been confirmed.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/7848e8ef-a841-4a1c-929b-93191c342a7f)

**Comment by FedeGueli** [comment] 2023-06-18 15:02
Not sure how much it is going well. next week we will see if better closing this one.

**Closed as not planned** 2023-06-21 07:21 UTC
Labels: help wanted, Discussion, Saltation, Artifact?
