### ISSUE TITLE
XDV.1.5 with ORF1a:A1473V (nsp3_A655V), ORF1a:H1141Y (nsp3_H323Y), ORF3a:R134H, ORF1a:I2709V (nsp3_I1891V), ORF1a:P4197S (nsp9_P57S), and S:F59S (8 seqs, 4 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#2073] opened 2024-09-21 11:55 UTC
**Defining Mutations:** `XDV.1.5` > `C4683T(ORF1a:A1473V), T15573C` > `C3686T(ORF1a:H1141Y), G25793A(ORF3a:R134H)` > `A8390G(ORF1a:I2709V), C12854T(ORF1a:P4197S), T21738C(S:F59S), C25671T`
**Query:** `A8390G, C12854T`
**Earliest seq:** 24-07-17 (`EPI_ISL_19297920`, Ontario, Canada)
**Latest seq:** 24-09-10 (`EPI_ISL_19427370`, _GBW_ ex. Netherlands)
**Sampled Countries:** USA:3 (all _GBW_ ex. China and Netherlands), China:2 (HB), Singapore:2, Canada:1 (ON)

<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/ON-KHS-03387-v1/2024
Hubei/HCDC-JZ7079/2024
Hubei/HCDC-WH6866/2024
Singapore/R46MQ69/2024
Singapore/R51MQ37/2024
USA/CA-GBW-GKISBBBC80298/2024
USA/CA-GBW-GKISBBBD44672/2024
USA/CA-GBW-GKPLAAAA30934/2024
```

epi_isl accessions:
`EPI_ISL_19297920, EPI_ISL_19311929, EPI_ISL_19384883, EPI_ISL_19388700, EPI_ISL_19412253, EPI_ISL_19412299, EPI_ISL_19427370, EPI_ISL_19429289`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3cb93_eae350.json?label=id:node_7189619
![image](https://github.com/user-attachments/assets/5c9457c3-cfc0-49d4-bf5f-9a96e49623b8)

**Trivia:**
- Already have additional spike mutation `S:T22N`; `T29672C` would have extended hypothetical _ORF10_ with a few AA: `QQSLISV*`

**Comment by FedeGueli** [comment] 2024-09-21 16:05
Thx for spotting again it is a duplicate of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1840

**Closed** 2024-09-21 16:05 UTC
Labels: duplicate

**Comment by FedeGueli** [comment] 2024-09-21 20:49
> > Thx for spotting again it is a duplicate of #1840
> 
> oh didn't see that. can't find it with nuc search though.

yeah because it was a duplet only  mentioned in the original XDV.1.5 issue (that is the one linked) then it grew and we changed the proposal. It is an easy and handy way to refresh sub branhces but a bit sad to lose the original proposal>lineage designation and sometmes the further sub branch proposals are incomplete until transferred in the main Pango page.

**Comment by aviczhl2** [comment] 2024-09-21 23:45
Maybe we can keep this open and close down that one if you edit the proposal to include the S:T22N sub-branch?
