### ISSUE TITLE
LF.8.1.1 + Orf6:I33M and S:K478T  (4 samples , 3 Places) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2118] opened 2024-10-05 11:59 UTC
LF.8.1.1 is evolving in a stepwise manner, as in https://github.com/sars-cov-2-variants/lineage-proposals/issues/1929 it is proposed a lineage with 478E , here i would like to propose its sublineage with 478T

LF.8.1.1 >> ORF1a:L4391F (C13436T) > Orf6:I33M (A27300G) > S:K478T (rev A22995C)
Query: C13436T,A27300G 
Samples: 6 ( 4 with 478T) 
Places: Qatar (GBW), Uae (GBW), Virginia (US)
Tree:
<img width="1159" alt="Screenshot 2024-10-05 alle 13 59 05" src="https://github.com/user-attachments/assets/3e2cd920-41bb-4ae7-9240-94f31f0237fa">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice41_genome_test_62fb8_11d3e0.json?label=id:node_6978486

**Comment by aviczhl2** [comment] 2024-10-05 12:43
duplicate of #1982

**Closed** 2024-10-05 22:50 UTC
Labels: S:478, Reversions, duplicate, LF.8.1.1

**Comment by FedeGueli** [comment] 2024-10-05 22:52
> duplicate of #1982
> 
> you decide whether to re-open the previous one or keep this one as it is more updated.

Ok thx closing this ( It is for this reason i m trying to cross mention issues  )
