### ISSUE TITLE
JN.1.4/FL.15 recombinant (25 seqs, 4 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1177] opened 2023-12-14 06:02 UTC
JN.1.4+C27810T(rev), G27915T, T28297C, C28846T, A28958C(rev)

Orf7b:L19F(rev)
Orf8:G8*
Orf9b:I5T
N:K229Q(rev)

JN.1.4--FL.15*
Breakpoint between 26834 and 27809

GISAID query: T28297C, C897A, C28846T, G27915T, C774T by @ryhisner ( former query:T28297C,T18453C,C774T )
No. of seqs:4 (USA)

First: EPI_ISL_18623642, USA-CA, 2023-11-7
Latest: EPI_ISL_18604137, USA-OH, 2023-11-23

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23818_a99740.json?label=id:node_11052444)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/03b42050-4951-40f1-8254-c1b51d4e72b1)

**Comment by aviczhl2** [comment] 2023-12-29 08:44
+1 Israel

**Comment by aviczhl2** [comment] 2024-01-02 18:00
+1 Denmark

**Comment by FedeGueli** [comment] 2024-01-03 08:30
+2 Canada 

Pleasee propose once it reaches 25

**Comment by FedeGueli** [comment] 2024-01-07 23:40
This jumped to 22 with a batch from NYC ( hence Ryan spotted and proposed the duplicate of this , i think)

**Comment by FedeGueli** [comment] 2024-01-07 23:41
Please propose it

**Comment by ryhisner** [comment] 2024-01-08 00:13
You have to include C28664T in the query or else you get 3-4 unrelated sequences—and that number will probably increase as time goes on. There are really only 18 sequences in this lineage. C28664T is an FL.15* mutation, so I think it's safe to call this one a JN.1/FL.15* recombinant.

**Comment by FedeGueli** [comment] 2024-01-08 00:29
thanks @ryhisner i have edited the query cc @aviczhl2

**Comment by aviczhl2** [comment] 2024-01-08 01:47
> You have to include C28846T in the query or else you get 3-4 unrelated sequences—and that number will probably increase as time goes on. There are really only 18 sequences in this lineage right now, not 22. C28846T is an FL.15* mutation, so I think it's safe to call this one a JN.1/FL.15* recombinant.

Yeah that's a thing for BA.2.86/XBB recomb islands. Recombs with similar breakpoints gather together and somethings the root and sub-branch are actually different recombs.

**Comment by aviczhl2** [comment] 2024-01-08 01:55
> You have to include C28846T in the query or else you get 3-4 unrelated sequences—and that number will probably increase as time goes on. There are really only 18 sequences in this lineage right now, not 22. C28846T is an FL.15* mutation, so I think it's safe to call this one a JN.1/FL.15* recombinant.

For 4 seq withs 28846, only 1 seq without 28958( may be JN.1/other XBB.1+Orf9b:I5T recomb) , others seem to be JN.1 getting T28297C independently.

**Closed** 2024-01-12 06:25 UTC
Labels: recombinant, To be proposed, ORF9b, JN.1

**Comment by FedeGueli** [comment] 2024-01-16 20:06
Designated XDP via https://github.com/cov-lineages/pango-designation/commit/2c803975c17c274fed109fe7fb90daa7bbaf106b
