### ISSUE TITLE
KP.3.1.1 subbranch with M:I80L and Orf9b:R47P(14, 4 countries)

### ISSUE THREAD

**Issue by Over-There-Is** [sars-cov-2-variants/lineage-proposals#2055] opened 2024-09-18 13:03 UTC
KP.3.1.1> C1441T> A26760C(M:I80L), G28423C(Orf9b:R47P)
Query: A26760C, G28423C

Earliest sequence: 07-22 New York City, New York, USA EPI_ISL_19310813
Latest sequence: 09-06 Utah, USA EPI_ISL_19416909
Regions detected: US 5, Italy 4, Denmark 3, Canada 2

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5e932_acec00.json?c=country&label=id:node_7033124
![image](https://github.com/user-attachments/assets/9c7c3375-a6e7-4241-86fb-c936a839c952)

EPI_ISL_19310813, EPI_ISL_19340122, EPI_ISL_19378173,
EPI_ISL_19378191, EPI_ISL_19378985, EPI_ISL_19410881,
EPI_ISL_19410913, EPI_ISL_19410917, EPI_ISL_19411048,
EPI_ISL_19412118, EPI_ISL_19416249, EPI_ISL_19416902,
EPI_ISL_19416909, EPI_ISL_19420984

**Comment by FedeGueli** [comment] 2024-09-18 21:07
duplicate of #2026

**Comment by FedeGueli** [comment] 2024-09-18 21:07
> duplicate of #2026

ahaha you were the proposer!

**Closed by FedeGueli** 2024-09-18 21:07 UTC
Labels: duplicate
