### ISSUE TITLE
EG.5.1 with ORF1b:T2084I (nsp15_T33I), S:E554K, S:L452R and N:ins238Q (49 seqs, 7 countries) 20% in Guatemala

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1215] opened 2023-12-22 11:34 UTC
**Defining Mutations:** `EG.5.1` > `C19718T(ORF1b:T2084I)` > `A916G, G7936T, A11326G, C28603T, ins28987CAA(N:ins238Q)` > `G23222A(S:E554K)` > `T22917G(S:L452R)`
**Query:** `G7936T, C19718T, T22917G` _OR_ `G7936T, C19718T, G23222A`
**Earliest seq:** 2023-09-19 (`EPI_ISL_18475363`, Guatemala)
**Latest seq:** 2023-12-07 (`EPI_ISL_18642253`, Noord-Brabant, Netherlands)
**Sampled Countries:** Guatemala (11), Netherlands (4), USA (1: UT)

<details><summary>Genomes: </summary>

`EPI_ISL_18475363, EPI_ISL_18522395, EPI_ISL_18642237, EPI_ISL_18642247, EPI_ISL_18642253, EPI_ISL_18646624, EPI_ISL_18669852-18669855, EPI_ISL_18669859, EPI_ISL_18669863-18669868, EPI_ISL_18669871`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_d155_570fd0.json?label=id:node_3425604
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/c20a1bb5-f32c-4c02-a5f2-91fb2ebecfe9)

**Trivia:**
- The outlier `hCoV-19/Guatemala/2228-DLNS/2023|EPI_ISL_18291419|2023-08-18` and `Guatemala/DLNS-2356/2023|EPI_ISL_18475363|2023-09-19` has bad coverage on Spike (missing everthing after `spike_493`) so `S:L452R` could be part of the mini-saltation
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/848161ab-a3ae-46fc-9cf6-f42df90bce05)
- The former sequence also has `N:ins238Q (ins28987CAA)`
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/7b62e86e-6033-4704-be26-d5524c9b75b1)

**Comment by FedeGueli** [comment] 2023-12-23 06:50
This seems fast.

**Comment by JosetteSchoenma** [comment] 2023-12-23 07:21
> This seems fast. maybe just a very good start.
> 
> ![Schermata 2023-12-23 alle 07 51 59](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d53448b6-0d61-4614-9f66-aaf6a57065f6)
> 
> cc @JosetteSchoenma is in Netherlands.
> cc @ryhisner please take a look at this insertion in N.
> 
> 
The latest 6 Dutch ones look like a cluster. Same lab, same provence. I don't expect they will have provided ages, but I will check.

**Comment by ryhisner** [comment] 2023-12-24 22:05
This insertion is fairly homoplasic, actually. It comes in the middle of a long stretch of "CAA" glutamines, so presumably it causes some sort of stutter in the RdRp. PolyQ is a thing, but I don't know much about it other than that it's associated with Huntington's Disease.  
<img width="812" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/39ad7c8f-68d8-4465-a8e9-6c282a68aa37">

It's somewhat reminiscent of the ORF3a:ins103P (CCC), or occasionally ins103PP (CCCC) or ins103PPP (CCCCCCCCC). But in that case I'm pretty sure its the "slippery" stretch of mostly T's and A's on its 3' end that, along with the consecutive C's at, 25700-25703, that are the cause. Best evidence for this is that its enormously disproportionately presence in sequences with ORF3a:L106F, which converts one of the only non-A-or-T nucleotides from C to T. 
<img width="799" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/b03e8154-df1e-4d4a-b06a-ae0b47d0c542">

**Comment by FedeGueli** [comment] 2023-12-26 08:17
> This insertion is fairly homoplasic, actually. It comes in the middle of a long stretch of "CAA" glutamines, so presumably it causes some sort of stutter in the RdRp. PolyQ is a thing, but I don't know much about it other than that it's associated with Huntington's Disease. <img alt="image" width="812" src="https://private-user-images.githubusercontent.com/33738461/292690473-39ad7c8f-68d8-4465-a8e9-6c282a68aa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg5MTEsIm5iZiI6MTcwMzU3ODYxMSwicGF0aCI6Ii8zMzczODQ2MS8yOTI2OTA0NzMtMzlhZDdjOGYtNjhkOC00NDY1LWE4ZTktNmMyODJhNjhhYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MWI2Y2U1ODE0NzQwNWI0MzEzOTQwZDE3ODdlOTQ5YjYzMGY3YzY4MGQ4OWVhZjU0MjhhMjhkZjdiZDQyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixD-hjaZ1h7Dg1ENIAsSymDmA6aYb0mlSJMQQiwCBxA">
> 
> It's somewhat reminiscent of the ORF3a:ins103P (CCC), or occasionally ins103PP (CCCCCC) or ins103PPP (CCCCCCCCC). But in that case I'm pretty sure its the "slippery" stretch of mostly T's and A's on its 3' end that, along with the consecutive C's at, 25700-25703, that are the cause. Best evidence for this is that its enormously disproportionately presence in sequences with ORF3a:L106F, which converts one of the only non-A-or-T nucleotides from C to T. <img alt="image" width="799" src="https://private-user-images.githubusercontent.com/33738461/292690624-b03e8154-df1e-4d4a-b06a-ae0b47d0c542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg5MTEsIm5iZiI6MTcwMzU3ODYxMSwicGF0aCI6Ii8zMzczODQ2MS8yOTI2OTA2MjQtYjAzZTgxNTQtZGYxZS00ZDRhLWIwNmEtYWUwYjQ3ZDBjNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZDBhYWVmYWMzYjJhODE1ZDJkMjc0YmQ1NmViNzE2ZDBhNWMzMGQyZTY5ODYwZGI0ZTMwNDNmNTVlYzg3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bylIajJWmyfa21fNcfIlsNzPwPYFnXmTVjepKcvo1vA">

Thank you Ryan didnt notice it before thx!

**Comment by FedeGueli** [comment] 2023-12-26 08:19
19-21 sequences last caught in a traveller from Guatemala

**Comment by FedeGueli** [comment] 2023-12-30 07:24
20-22 illinois

**Comment by FedeGueli** [comment] 2024-01-22 11:32
0 samples from january yet

**Comment by FedeGueli** [comment] 2024-02-12 00:11
31

**Comment by FedeGueli** [comment] 2024-02-21 14:43
48 , a batch of this lineage has been uploaded from Guatemala mostrly from December 2023, but it has been sampled multiople times recently in USA too.  It represents 20% of sequences in Guatemala during December 2023

**Comment by FedeGueli** [comment] 2024-03-03 10:35
closing it

**Closed by FedeGueli** 2024-03-03 10:35 UTC
Labels: Insertion, Emerged in an undersampled area, S:452, S:554
