### ISSUE TITLE
XBB.1.16(Main page #2404)/BA.2.86.1 recombinant. 15 seq, Japan

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#1084] opened 2023-11-15 23:11 UTC
Description: XBB.1.16([Main page #2404](https://github.com/cov-lineages/pango-designation/issues/2404))/BA.2.86.1 recombinant. 1 breaking point, Spike from BA.2.86.1
Private mutations: C12115T
C3177T, C3587T and C3944A in XBB.1.16, C26078T in BA.2.86.1
Breakpoint: between nucleotide 11957 and 12729
One sequence from: 2023-10-11 from Japan/Kanagawa
Countries circulating: Japan
GISAID query: C3944A,C12115T (edited, by @aviczhl2 in #1153)
Sample: EPI_ISL_18505932
Nextclade:
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/0d72095d-fa83-4265-be56-d51cdbc71d5c)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/0025975f-d623-42b0-881e-8708187d0a0f)

**Comment by JosetteSchoenma** [comment] 2023-11-23 12:22
I added C9866T to the query, to avoid catching the Dutch JN.1 EPI_ISL_18536294.

**Comment by aviczhl2** [comment] 2023-12-21 06:51
Oh #1153 seems to be duplicate of this. I'll close that one.

**Comment by aviczhl2** [comment] 2024-01-16 00:05
+4 Japan, 7 now

**Comment by aviczhl2** [comment] 2024-01-18 02:02
+1 more from Japan

**Comment by aviczhl2** [comment] 2024-01-25 17:04
9 now

**Comment by aviczhl2** [comment] 2024-02-05 04:20
12 now

**Comment by FedeGueli** [comment] 2024-02-10 13:03
14 now, @JosetteSchoenma please propose it.

**Comment by JosetteSchoenma** [comment] 2024-02-21 15:04
15th

@aviczhl2 his query is better. I will remove mine.

I am putting this on my "to propose list".

**Comment by FedeGueli** [comment] 2024-02-26 09:26
Thx for proposing

**Closed** 2024-02-26 09:26 UTC
Labels: recombinant, To be proposed, BA.2.86

**Comment by FedeGueli** [comment] 2024-03-27 06:37
Designated XDU via https://github.com/cov-lineages/pango-designation/commit/b521ee22fdaa7c575d25895c92a4a630fa7511a0
