### ISSUE TITLE
XDV.1.5.1 + S:A435S in Hubei (3)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#2274] opened 2024-12-09 13:57 UTC
While XDV.1 is keeping a dominant position in China in November around 70% prevalence with 2/3 of them being NB.1,
Hubei is currently not uploading a lot of sequences but among the few recent ones there were two of this sub lineage of XDV.1.5.1 with S:A435S convergently with KP.3.1.1/ XDY and other lineages

Defining:
XDV.1.5.1 >  C28610T >  C6896T, S:A435S (G22865T), G25644T, ORF3a:D155H (G25855C)
Query:C28610T ,  C6896T,  G22865T
Samples: 3 Hubei (Enshi, Wuhan)
Tree:
<img width="1175" alt="Screenshot 2024-12-09 alle 14 55 46" src="https://github.com/user-attachments/assets/2de31881-08e8-49ff-9d0b-c63c9db63b1e">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_63d57_6d34c0.json?c=userOrOld&label=id:node_7057457

**Comment by xz-keg** [comment] 2024-12-12 03:34
duplicate of #2228

**Closed** 2024-12-12 03:34 UTC
Labels: S:456, S:478, S:435, S:184, duplicate, XDV.1

**Comment by FedeGueli** [comment] 2024-12-15 21:54
> duplicate of #2228

thx i didnt match the two
