### ISSUE TITLE
Question about variants

### ISSUE THREAD

**Issue by abergi** [sars-cov-2-variants/lineage-proposals#1595] opened 2024-06-04 13:17 UTC
Dear all.

I've been viewing the issues section for a while and I would like to ask a few questions, if anyone could please reply. I know that this issue section might not be suitable but I don't know where else to ask. Please if anyone has the time to reply to me and help me understand a few things. 

I've recently been reading about the new variants KP.1, KP.2, KP.3 and KP.4, and I've read an article https//www.williamhaseltine.com/analyzing-the-emergence-of-covid-variant-kp-2-and-its-potential-impact/ about KP.2 variant. 

1. Have you noticed the mutations  D614G in the spike, P323L in NSP12, and the C241U too?
2. Can those mutations make those variants more severe to someone who was never infected before ?
3. When they say "Furthermore, it is worth mentioning that this virus, along with most sequenced variants throughout the Covid-19 epidemic, shares three mutations with the first departing variant from the original Wuhan virus. These are D614G in the spike, P323L in NSP12, and the C241U synonymous mutation in the 5’ end of the virus."  I looked up the specific spike mutations and I found this https://genominfo.org/journal/view.php?doi=10.5808/GI.2020.18.4.e44 suggesting that those spike proteins are associated with more severe infection. Could that be the case with KP.2 (a step back to Alpha strain?)? I mean, earlier variants are connected to many health risks, including depletion of T cell count. 
4. Do the other variants, KP.1, KP.3, KP.4  have those mutations as well (if you have analyzed them)?
5. When they say "infection with KP.2 could be very serious, and they should exercise caution." Does that make KP variants to be able to cause more severe disease than JN.1?
6. Also, were those spike proteins in other Omicron variants too? For example, on JN.1 variants?
7. when they say "The synonymous mutations do not change the virus’s amino acid sequence, but they do influence the tertiary structure of its RNA" they mean it could still act as the earlier Omicron variants?
8. On another article https://edition.cnn.com/2024/05/23/health/kp2-covid-flirt-variant-wellness/index.html, it says "The good news is that KP.2 does not appear to cause more severe disease. Indeed, hospitalizations associated with Covid-19 are at record lows." Isn't too early to know that?
9. I read somewhere that it needs a high viral dose of KP.2 for someone to get infected, is this true based on the current data and spike mutations on it?
10. Do JN.1 variants and now the newer variants KP still carry the prion region like earlier variants?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8878784/
11. Based on all the sequences you've seen, is there one variant that carried less mutations and was very mild?
12. I read a few studies, and was curious if the current variants can cause cancer in long term.
https://www.nature.com/articles/s41467-024-48370-6
https://www.biorxiv.org/content/10.1101/2024.04.12.589252v1
https://pubmed.ncbi.nlm.nih.gov/37230238/

Thank you for your time.

**Comment by Mydtlwn** [comment] 2024-06-04 15:53
https://nextstrain.org/ncov/gisaid/global/6m

**Comment by Mydtlwn** [comment] 2024-06-04 16:12
It's worth noting that if you find mutations existing in most of the currently circulating branches on the website, there are only a few scenarios. One is that they are convergent mutations, such as the current S:R346T, S:F456L, S:T572I, S:S31del. The other is that they were defined earlier and have been inherited by these branches ever since.

**Comment by ryhisner** [comment] 2024-06-04 18:55
@abergi, I'll try to answer some of your questions as best I can, and I'll try to give an idea of the level of confidence I feel in the answers. 

> 1. Have you noticed the mutations  D614G in the spike, P323L in NSP12, and the C241U too?

All three of these mutations have been in virtually every Covid variant since mid-2020 with only a small number of unimportant exceptions, all of them in 2020-2021. 

I find it fascinating that the only exceptions to C241T and NSP12_P323L (more commonly called ORF1b:P314L here) are in the hypermutated cryptic wastewater variants and a handful of extreme, long-term chronic-infection sequences. Why that should be is a total mystery, but I think it proves that even C241T has a real effect, though what its function might be is totally unknown, as far as I'm aware. In any case, those sequences are confined to individuals and rarely, if ever, transmit, at least so far. 

> 2. Can those mutations make those variants more severe to someone who was never infected before ?
Again, they've all been universal for a long time—the entire pandemic in most places, so they couldn't cause any change unless compared to February 2020 or thereabouts.  

> 3. When they say "Furthermore, it is worth mentioning that this virus, along with most sequenced variants throughout the Covid-19 epidemic, shares three mutations with the first departing variant from the original Wuhan virus. These are D614G in the spike, P323L in NSP12, and the C241U synonymous mutation in the 5’ end of the virus."  I looked up the specific spike mutations and I found this https://genominfo.org/journal/view.php?doi=10.5808/GI.2020.18.4.e44 suggesting that those spike proteins are associated with more severe infection. Could that be the case with KP.2 (a step back to Alpha strain?)? I mean, earlier variants are connected to many health risks, including depletion of T cell count.

No one knows anything with certainty about KP.2 or any of the very recent variants, but I consider it highly unlikely that the degree of disease severity caused by them will be substantially different than the JN.1 variants from which they all descend. The only time we really need to worry about a serious change in disease severity is when a completely novel lineage emerges. When BA.2.86 (the parent lineage of all JN.1 and KP variants) first emerged, it was reasonable to suspect that disease severity might change. But it turned out there wasn't any real change in severity; I haven't seen any evidence anyway. 

> 5. When they say "infection with KP.2 could be very serious, and they should exercise caution." Does that make KP variants to be able to cause more severe disease than JN.1?
No one knows. Personally, I think it's extremely unlikely there's any real change in disease severity between KP.2 and JN.1. The differences between JN.1 and all the KP lineages are really quite small in the large scheme of things. They make a big enough difference in antibody evasion to allow more infections to occur and for the newer variants to grow relative to plain JN.1, but there's nothing that indicates they would change the nature of the resulting disease.  

> 7. when they say "The synonymous mutations do not change the virus’s amino acid sequence, but they do influence the tertiary structure of its RNA" they mean it could still act as the earlier Omicron variants?
This has nothing to do with earlier variants. It's just saying that even synonymous mutations (which don't change the amino acids produced) could conceivably make a difference in the functioning of the virus. Most probably do not though. 


> 8. On another article https://edition.cnn.com/2024/05/23/health/kp2-covid-flirt-variant-wellness/index.html, it says "The good news is that KP.2 does not appear to cause more severe disease. Indeed, hospitalizations associated with Covid-19 are at record lows." Isn't too early to know that?
Government agencies and major media have a really annoying tendency to assert that "there's no evidence" each new variant causes more severe disease. They have said this with every variant ever, including Delta. Of course it's too soon to know. However, like I said earlier, past experience has been that stepwise spike mutations like the ones in the new variants do not cause any noticeable change in disease severity.


> 9. I read somewhere that it needs a high viral dose of KP.2 for someone to get infected, is this true based on the current data and spike mutations on it?
Sounds like nonsense to me. If you know the source of that claim, I'd like to see it. 


> 11. Based on all the sequences you've seen, is there one variant that carried less mutations and was very mild?
If anything, I think it's more likely that as spike mutations accumulate, disease severity might slightly decline. I'm not at all certain about this, but I believe there was some observational evidence showing that CH.1.1 & its sublineages were somewhat less severe than other variants circulating at the same time. CH.1.1 really piled on the spike mutations, which helped evade antibodies but may have weakened ACE2 binding and other virus functions. Again, I'm not at all certain about this one. 


> 12. I read a few studies, and was curious if the current variants can cause cancer in long term.
I'm pretty sure no one knows. Long-term effects, by definition, take a long time to emerge, and I don't think there's any reliable way of predicting them.

**Comment by FedeGueli** [comment] 2024-06-04 23:15
> Dear all.
> 
> I've been viewing the issues section for a while and I would like to ask a few questions, if anyone could please reply. I know that this issue section might not be suitable but I don't know where else to ask. Please if anyone has the time to reply to me and help me understand a few things.
> 
> I've recently been reading about the new variants KP.1, KP.2, KP.3 and KP.4, and I've read an article https//www.williamhaseltine.com/analyzing-the-emergence-of-covid-variant-kp-2-and-its-potential-impact/ about KP.2 variant.
> 
> 1. Have you noticed the mutations  D614G in the spike, P323L in NSP12, and the C241U too?
> 2. Can those mutations make those variants more severe to someone who was never infected before ?
> 3. When they say "Furthermore, it is worth mentioning that this virus, along with most sequenced variants throughout the Covid-19 epidemic, shares three mutations with the first departing variant from the original Wuhan virus. These are D614G in the spike, P323L in NSP12, and the C241U synonymous mutation in the 5’ end of the virus."  I looked up the specific spike mutations and I found this https://genominfo.org/journal/view.php?doi=10.5808/GI.2020.18.4.e44 suggesting that those spike proteins are associated with more severe infection. Could that be the case with KP.2 (a step back to Alpha strain?)? I mean, earlier variants are connected to many health risks, including depletion of T cell count.
> 4. Do the other variants, KP.1, KP.3, KP.4  have those mutations as well (if you have analyzed them)?
> 5. When they say "infection with KP.2 could be very serious, and they should exercise caution." Does that make KP variants to be able to cause more severe disease than JN.1?
> 6. Also, were those spike proteins in other Omicron variants too? For example, on JN.1 variants?
> 7. when they say "The synonymous mutations do not change the virus’s amino acid sequence, but they do influence the tertiary structure of its RNA" they mean it could still act as the earlier Omicron variants?
> 8. On another article https://edition.cnn.com/2024/05/23/health/kp2-covid-flirt-variant-wellness/index.html, it says "The good news is that KP.2 does not appear to cause more severe disease. Indeed, hospitalizations associated with Covid-19 are at record lows." Isn't too early to know that?
> 9. I read somewhere that it needs a high viral dose of KP.2 for someone to get infected, is this true based on the current data and spike mutations on it?
> 10. Do JN.1 variants and now the newer variants KP still carry the prion region like earlier variants?
>     https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8878784/
> 11. Based on all the sequences you've seen, is there one variant that carried less mutations and was very mild?
> 12. I read a few studies, and was curious if the current variants can cause cancer in long term.
>     https://www.nature.com/articles/s41467-024-48370-6
>     https://www.biorxiv.org/content/10.1101/2024.04.12.589252v1
>     https://pubmed.ncbi.nlm.nih.gov/37230238/
> 
> Thank you for your time.

I agree with Ryan, i would add that severity is the last thing we could determine  so it takes some months to be sure of that, but the tendency as of today is toward an iperspecialization in Upper resp. airways and maybe in GUT (still to be proven). So the trend is not toward lower respiratory track where this virus has done the most damages in the early 2020-21 waves. Anyway this virus could be still an issue for fragile people , elderly people and can cause long covid , an autoimmune response that can disable temporarily or for prolonged time ability to do daily simple routines.  So don't underestimate it. but also don't panick for every new variants. Luckily we are on the virus and we are still able to find dominant lineages from less than 10 sequences, that means we gain 2months to track its growth and to eventually sense a signal on severity ( hard to but possible). So i would be quiet but taking care. hugs.

**Comment by abergi** [comment] 2024-06-05 20:54
Hello @FedeGueli @ryhisner and @Mydtlwn. Thank you so much for your kind replies. I really appreciate it. 
I felt so embarrassed to post in here, because you guys work so hard to analyze the variants and tell the changes of them and my post felt a bit off the topic. I'm glad that it was kept posted. Your replies make the things more clear for me. 

I've been stressing a lot lately. I'm 29 years old and don't have any health issues but by the time pandemic started, I've always been very scared to go outside (still am). After almost five years, I expected that the pandemic will do it's circle and the virus would be milder or something like the other coronaviruses. Reading those studies, make me think that in long term, all those who got infected, could develop some kind of issues (cancer being the scariest). For example: 

- Regarding this study: https://www.nature.com/articles/s41467-024-48370-6 

Does that affect everyone that gets infected with it or depends if it's treated early? They analyzed a 2020 variant, and they say there is no evidence that it causes cancer, and that structural re-arrangement are stronger in people with long covid effects. Also that it is likely that other, more recent variants lead to similar effects, but this has not been shown.

- Is the prion region still on the current variants? 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8878784/

- https://www.forbes.com/sites/williamhaseltine/2023/10/26/jn1-the-odd-man-out-among-omicron-sublineages/ "Many spike protein mutations are among those we have seen in previous variants of concern, such as E484K and P681R, which were first identified in the Alpha and Beta variants of SARS-CoV-2 in early 2021. Why those mutations fell out of circulation in the Omicron family of variants is unclear, but their reemergence in JN.1 is noteworthy."  

>I read somewhere that it needs a high viral dose of KP.2 for someone to get infected, is this true based on the current data and spike mutations on it?
>Sounds like nonsense to me. If you know the source of that claim, I'd like to see it.

I looked up again but can't seem to be able to find it. Maybe it was talking about KP.1. I will try to find it

>toward an iperspecialization in Upper resp. airways and maybe in GUT (still to be proven)

I read when Omicron started, that it affects mainly upper resp airways, but how could someone knows? I read that covid (not sure if Omicron) can also hide in the body (like HIV) or in gut like you said and stay there. Will nisin help to clear the gut? 

Does that makes new variants with mutations from earlier variants from 2020-2021 possibly more severe?

Everyone has moved on since the last 2 years, and I rarely see anyone mask anymore, even the elderly. So now, I'm not sure at which point we are on the pandemic. I thought that as years go by, the virus would be similar to other seasonal coronaviruses. When I first heard about BA 2.86 variant, I was surprised cause I thought that the variant that it came from (BA.2.75) was declining (was like 1%?) and thought that could be more severe I really regretted that I wasn't infected with omicron. And now I'm just uncertain , what if future variants can be more severe (?)

**Comment by FedeGueli** [comment] 2024-06-05 22:00
> Hello @FedeGueli @ryhisner and @Mydtlwn. Thank you so much for your kind replies. I really appreciate it. I felt so embarrassed to post in here, because you guys work so hard to analyze the variants and tell the changes of them and my post felt a bit off the topic. I'm glad that it was kept posted. Your replies make the things more clear for me.
> 
> I've been stressing a lot lately. I'm 29 years old and don't have any health issues but by the time pandemic started, I've always been very scared to go outside (still am). After almost five years, I expected that the pandemic will do it's circle and the virus would be milder or something like the other coronaviruses. Reading those studies, make me think that in long term, all those who got infected, could develop some kind of issues (cancer being the scariest). For example:
> 
> * Regarding this study: https://www.nature.com/articles/s41467-024-48370-6
> 
> Does that affect everyone that gets infected with it or depends if it's treated early? They analyzed a 2020 variant, and they say there is no evidence that it causes cancer, and that structural re-arrangement are stronger in people with long covid effects. Also that it is likely that other, more recent variants lead to similar effects, but this has not been shown.
> 
> * Is the prion region still on the current variants?
>   https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8878784/
> * https://www.forbes.com/sites/williamhaseltine/2023/10/26/jn1-the-odd-man-out-among-omicron-sublineages/ "Many spike protein mutations are among those we have seen in previous variants of concern, such as E484K and P681R, which were first identified in the Alpha and Beta variants of SARS-CoV-2 in early 2021. Why those mutations fell out of circulation in the Omicron family of variants is unclear, but their reemergence in JN.1 is noteworthy."
> 
> If future variants include spike mutations from earlier variants which were more severe (2020-2021), does that make them more severe?
> 
> > I read somewhere that it needs a high viral dose of KP.2 for someone to get infected, is this true based on the current data and spike mutations on it?
> > Sounds like nonsense to me. If you know the source of that claim, I'd like to see it.
> 
> I looked up again but can't seem to be able to find it. Maybe it was talking about KP.1. I will try to find it
> 
> > toward an iperspecialization in Upper resp. airways and maybe in GUT (still to be proven)
> 
> I read when Omicron started, that it affects mainly upper resp airways, but how could someone knows? I read that covid (not sure if Omicron) can also hide in the body (like HIV) or in gut like you said and stay there. Will nisin help to clear the gut?
> 
> Everyone has moved on since the last 2 years, and I rarely see anyone mask anymore, even the elderly. So now, I'm not sure at which point we are on the pandemic. I thought that as years go by, the virus would be similar to other seasonal coronaviruses. When I first heard about BA 2.86 variant, I was surprised cause I thought that the variant that it came from (BA.2.75) was declining (was like 1%?) and thought that could be more severe I really regretted that I wasn't infected with omicron. And now I'm just uncertain , what if future variants can be more severe (?)

First for sharing your thoughts, my advice is to follow guidelines by public health agencies and to get your updated booster everytime it is released when available for your aage in your country , that is the biggest tool to avoid undesired counter effects of the infection that in a young healthy people rarely  are related to the acute phase (even fi still possible). Consider that we have some approved treatment for Covid itself as the inhibithors of proeteases like the one patented by Pfizer, that is still working well and in the unlucky event someone reaches a critical point in its infection could be prescribed in hospital. What i am trying to tell you that we are not in 2020-2021 and the virus is not the same of Delta or first waves. The mutations linked to its attenuation have never been mutated  since the Omicron emergence and whiile it is true that some sublineages (as in the past BQ.1.2.2) could have a specific increase of severity (or feared increase in severity) we never see one being associated to a growth advantage. This means that likely reverting to a different preference (lungs) is not successful as of today, and that makes sense cause trasmission and fast transmission especially happen when Upper resp tract is affected (sneezing,speaking and etc etc etc) .  This doesn't mean SC2 is nothing or something not to care about, but be sure that if something worsens you will know by official accounts of Public health agencies, as i said above when you get boosted with the recommended timing you are in the best situation to cope with this virus.

**Comment by FedeGueli** [comment] 2024-06-05 22:15
Anyway feel free to contact me in DM on twitter : https://x.com/siamosolocani , everytime you have questions (that i can answer, consider i m just  a citizen too). closing this for now.

**Closed by FedeGueli** 2024-06-05 22:15 UTC
Labels: help wanted

**Comment by abergi** [comment] 2024-06-06 11:16
@FedeGueli @ryhisner Thank you so much Federico. 

Ryan regarding your question where they said, KP.2 is less infectious. its here, this is a different article a newer one but they say the same plus that something is going on. These all is what I read and I worry. Is it becoming more severe? I also read a few issues here, and there is something you call as reversions to original virus or SARS1. What does this mean?

>“It seems it is less [infectious] compared to JN.1, but it’s more immune-evasive,” Michael said. “Something is going on there, which we don’t know exactly.”
https://fortune.com/well/2024/06/05/flirt-covid-19-omicron-variant-strains/

**Comment by aviczhl2** [comment] 2024-06-06 15:54
Hi Ryan, I have some different opinions. 

Despite number of mutations are not large in stepwise variants, I don't think we can safely assume there's no severity change. 

Given their immune escape and reproduction number change significantly under few mutations, it is possible that their severity changes within a few vital mutations. 

And there is evidence of this. For example, this research shows that XBB.1.16 is more severe than other variants circulating at the same time in Singapore, despite those variants are not too diverge in number of mutations. 
https://www.thelancet.com/action/showPdf?pii=S2666-6065%2823%2900167-0

But usually we have no evidence to prove either the severity change or not, especially before they infect most of the people. 

Outcome of single infections are highly random, severity is usually population-based, and to get such evidence we need to test and capture infection of people under a population and monitor health during their infection. Unfortunately it is hard to either capture all infections or monitor the health of the people infected under the current "live with virus is king" culture, and it is impossible to do that before people get infected unprotected.

**Comment by abergi** [comment] 2024-06-06 16:32
@aviczhl2 Hey Xu Zou. Do you believe these new variants KP.1, KP.2, KP.3, KP.4 could be more severe based on current data and spike mutations?
I've been checking CDC website and seems there is some small rise in hospitalizations although I believe we can't know because now the hospitals aren't required to report the incidents anymore. I'm not sure if there is any country tracking anymore. Not even for variants. 

https://covid.cdc.gov/covid-data-tracker/#variants-genomic-surveillance.

**Comment by aviczhl2** [comment] 2024-06-06 20:36
> @aviczhl2 Hey Xu Zou. Do you believe these new variants KP.1, KP.2, KP.3, KP.4 could be more severe based on current data and spike mutations? I've been checking CDC website and seems there is some small rise in hospitalizations although I believe we can't know because now the hospitals aren't required to report the incidents anymore. I'm not sure if there is any country tracking anymore. Not even for variants.
> 
> https://covid.cdc.gov/covid-data-tracker/#variants-genomic-surveillance.

No I don't. I believe they are unknown. They may be more severe or less severe or similar to other variants, but it's very hard to measure.

**Comment by FedeGueli** [comment] 2024-06-06 21:54
> > @aviczhl2 Hey Xu Zou. Do you believe these new variants KP.1, KP.2, KP.3, KP.4 could be more severe based on current data and spike mutations? I've been checking CDC website and seems there is some small rise in hospitalizations although I believe we can't know because now the hospitals aren't required to report the incidents anymore. I'm not sure if there is any country tracking anymore. Not even for variants.
> > https://covid.cdc.gov/covid-data-tracker/#variants-genomic-surveillance.
> 
> No I don't. I believe they are unknown. They may be more severe or less severe or similar to other variants, but it's very hard to measure.

I thinkmyou re right but even XBB.1.16 was less severe than Delta and first wave. There are fluctuations but still we have to observe a clear change of scenario in a competitive lineage with a different or first wave like presentation.

**Comment by aviczhl2** [comment] 2024-06-07 01:54
> I thinkmyou re right but even XBB.1.16 was less severe than Delta and first wave. There are fluctuations but still we have to observe a clear change of scenario in a competitive lineage with a different or first wave like presentation.

For severity of waves it largely depends on number of people infected, which is corresponding more to infection history than intrinstic severity of variants.

For regions without much infection of WT and Delta wave, their first wave, either starts from BA.2 or BA.5, are not better than the first wave or Delta wave of other regions. The Hong Kong BA.2 wave yields 200% excess mortality while the Macau BA.5 wave gives 300%+ excess mortality during their peaks. 

There's no region that takes XBB.1.16 as their first wave so hard to measure how it may perform if it being the first wave.

**Comment by FedeGueli** [comment] 2024-06-07 07:08
> > I thinkmyou re right but even XBB.1.16 was less severe than Delta and first wave. There are fluctuations but still we have to observe a clear change of scenario in a competitive lineage with a different or first wave like presentation.
> 
> For severity of waves it largely depends on number of people infected, which is corresponding more to infection history than intrinstic severity of variants.
> 
> For regions without much infection of WT and Delta wave, their first wave, either starts from BA.2 or BA.5, are not better than the first wave or Delta wave of other regions. The Hong Kong BA.2 wave yields 200% excess mortality while the Macau BA.5 wave gives 300%+ excess mortality during their peaks.
> 
> There's no region that takes XBB.1.16 as their first wave so hard to measure how it may perform if it being the first wave.

Yeah but the attenuation of all Omicron is clear, there was a shift toward URT from LRT that bringing an increase in transmissibility decreased severity, obviously the number of dead or severe cases is a function of the number of infected, in fact i would suggest to @abergi to modulate his prudence according to low vs high circulation of SC2

**Comment by aviczhl2** [comment] 2024-06-07 10:53
> Yeah but the attenuation of all Omicron is clear, there was a shift toward URT from LRT that bringing an increase in transmissibility decreased severity, obviously the number of dead or severe cases is a function of the number of infected, in fact i would suggest to @abergi to modulate his prudence according to low vs high circulation of SC2

Both XBB and JN.1 are very far away from original "Omicron” in all aspects. (number of mutations, antibody distance, etc.) I don't think it is safe to assume they are the same as original "omicron". 

If we count number of mutations, the distance between Delta and WT is 21, while distance between HK.25 and XBB is 37, the distance between most recent LG.1 and BA.2.86 is 20.  Sub-variants under the same major variant are already as distant as Delta against WT.

**Comment by FedeGueli** [comment] 2024-06-07 12:40
> > Yeah but the attenuation of all Omicron is clear, there was a shift toward URT from LRT that bringing an increase in transmissibility decreased severity, obviously the number of dead or severe cases is a function of the number of infected, in fact i would suggest to @abergi to modulate his prudence according to low vs high circulation of SC2
> 
> Both XBB and JN.1 are very far away from original "Omicron” in all aspects. (number of mutations, antibody distance, etc.) I don't think it is safe to assume they are the same as original "omicron". We have little evidence to prove or disprove any difference, but that doesn't mean same.
> 
> If we count number of mutations, the distance between Delta and WT is 21, while distance between HK.25 and XBB is 37, the distance between LG.1 and BA.2.86 is 20. Sub-variants under the same major variant are already as distant as Delta against WT. https://nextstrain.org/staging/nextclade/sars-cov-2

If severity has been back to WT we would have seen in the last huge winter wave, more there are the study by Stuart Turville showing that the direction took (Cleaved/Uncleaved ace preference)  by the evolution is further accelerating since JN.1 and with current circulating variants, although not clear what it means in real world it points at a clear direction. It could be reverted for sure at nay point but it is still not the case at the moment. SC2 is still a virus with a mayor impact in comparison to influenza even if attenuated btw.

**Comment by aviczhl2** [comment] 2024-06-07 13:27
> If severity has been back to WT we would have seen in the last huge winter wave, more there are the study by Stuart Turville showing that the direction took (Cleaved/Uncleaved ace preference) by the evolution is further accelerating since JN.1 and with current circulating variants, although not clear what it means in real world it points at a clear direction. It could be reverted for sure at nay point but it is still not the case at the moment. SC2 is still a virus with a mayor impact in comparison to influenza even if attenuated btw.

I'd like to discuss the difference on intrinstic severity and observed severity. 

Intrinstic severity is how hard the virus may hit the population assuming the virus infects the population without vac/infection history, 

Observed severity is how hard we observe the virus performing. It depends on many complex factors:

1:**Testing and reporting,**  if testing is limited and media don't report even if many people are sick, and people feel shamed testing or reporting sickness themselves, then it is hard to observe the severity. (maybe until your close relatives start dying at rapid speed, but that's doom. )

2: **Previous immunity**, previous vaccination/infection do help reduce severity. It works in two aspects, firstly they help reduce temporal infection, secondly they help reduce infection severity.
  If vac is limited and this is achieved via infection, then it just distribute the total infections to a longer period and the number of infections per person(and cumulative harm) will still not be reduced. 

3: **Instrinstic severity**, instrinstic severity may change from time to time. 

I think 1 & 2 play a giant role in reducing the observed severity. They also make it very hard to measure 3.

**Comment by abergi** [comment] 2024-06-07 13:59
@FedeGueli Unfortunately I said to be attending my master's graduation (outdoors) and now I'm not feeling too comfortable to be around all these people. I'm not sure what to do. I will probably have to take mask off in photos for a short time. However, the temperature here outside is around 40 Celsius degrees. 
@aviczhl2 might be right. I mean, when BA. 2.86 was out, I remember I read by some that we were talking about a complete different lineage something Omicron and Delta. Many countries have dropped testing (they bring it back only when there is a surge in cases and only for Hospitals. but they never report the cases or variants in public here after WHO declared the end of public health emergency. I thought CDC saw evidence and that's why they reduce their guidelines to one day and if you are fever free. 
Moreover I read that "Based on what CDC knows now, existing tests used to detect and medications used to treat COVID-19 appear to be effective with this variant. BA.2.86 may be more capable of causing infection in people who have previously had COVID-19 or who have received COVID-19 vaccines. " I'm not sure why is that.
https://www.cdc.gov/ncird/whats-new/covid-19-variant.html

More data "BA.2.86 pseudo-virus has been shown to
have high infectivity in CaLu-3 cells, with
this phenomenon thought to indicate a
change in disease severity (7,8).
However, there have been no reports of
changes in disease severity in studied
patients. A study from Denmark in ≥65-
year-old patients has reported no
difference in the odds of hospitalization
with JN.1 compared to non-BA.2.86
variant (OR: 1.15 [0.74-1.78]) (9). Similar
observations were reported by France
(10). However, for Singapore, JN.1 elderly
and younger cases had a lower risk of
hospitalization and severity (11). "
https://www.who.int/docs/default-source/coronaviruse/09022024_jn.1_ure.pdf

I also read that BA.2.86 entered cells like previous variants (eg, Delta)
"The researchers discovered that the Pirola variant, in contrast to all previously circulating Omicron variants, enters lung cells with high efficiency and uses the cellular enzyme TMPRSS2 for entry, thereby exhibiting surprising parallels to variants Alpha, Beta, Gamma and Delta that circulated during the first years of the pandemic"
https://www.fau.eu/2024/01/12/news/research/virus-uses-same-entry-pathway-into-lung-cells-as-earlier-covid-19-variants/

However the recorded data, showed lowest hospitalizations trend at some point with JN.1 (I think in April).

@aviczhl2 Do you think for someone who wasn't infected before could that KP newer variant cause more severe disease similar to Delta? That was my initially worry when BA 2.86 appeared. Because almost everyone got infected with Omicron variants, they have some immunity.

**Comment by aviczhl2** [comment] 2024-06-07 14:05
> @aviczhl2 Do you think for someone who wasn't infected before could that KP newer variant cause more severe disease similar to Delta? That was my initially worry when BA 2.86 appeared. Because almost everyone got infected with Omicron variants, they have some immunity.

Outcome on single infections are highly random, so even if I know such people it won't tell us anything I guess.

**Comment by abergi** [comment] 2024-06-07 14:40
> > Yeah but the attenuation of all Omicron is clear, there was a shift toward URT from LRT that bringing an increase in transmissibility decreased severity, obviously the number of dead or severe cases is a function of the number of infected, in fact i would suggest to @abergi to modulate his prudence according to low vs high circulation of SC2
> 
> Both XBB and JN.1 are very far away from original "Omicron” in all aspects. (number of mutations, antibody distance, etc.) I don't think it is safe to assume they are the same as original "omicron". We have little evidence to prove or disprove any difference, but that doesn't mean same.
> 
> If we count number of mutations, the distance between Delta and WT is 21, while distance between HK.25 and XBB is 37, the distance between LG.1 and BA.2.86 is 20. Sub-variants under the same major variant are already as distant as Delta against WT. https://nextstrain.org/staging/nextclade/sars-cov-2

What is WT?

**Comment by FedeGueli** [comment] 2024-06-07 16:11
Wild Type . the virus that spilled over in Wuhan

**Comment by aviczhl2** [comment] 2024-06-07 18:33
> That can happen? I don't understand then why everyone's say that it will eventually become a common cold

I don't think their's visible possibility for this. There's zero severe infectious disease becoming "common cold" after years of infections in history. Dengue, HIV, Ebola, smallpox, plague, cholera, malaria, do any of them become "common cold"? 

Unless we change the definition of "common cold" and adapt to a much worse outcome expectation of "cold" in population level. This seems working.

**Comment by abergi** [comment] 2024-06-07 18:51
> > That can happen? I don't understand then why everyone's say that it will eventually become a common cold
> 
> I don't think their's visible possibility for this. There's zero severe infectious disease becoming "common cold" after years of infections in history. Dengue, HIV, Ebola, smallpox, plague, cholera, malaria,polio, do any of them become "common cold" after years of circulation?
> 
> Unless we change the definition of "common cold" and adapt to a much worse outcome expectation of "cold" in population level. This seems to be what is happening.

Aren't coronaviruses suppose to mutate fast? I mean after looking up about other human coronaviruses, it says that they came from bats. 

The only thing I can compare this virus is the SARS-CoV-1 outbreak, which disappeared, but that is only for the results of it on people many years after.

**Comment by aviczhl2** [comment] 2024-06-07 19:19
> Aren't coronaviruses suppose to mutate fast? I mean after looking up about other human coronaviruses, it says that they came from bats.
> 
> The only thing I can compare this virus is the SARS-CoV-1 outbreak, which disappeared, but that is only for the results of it on people many years after.

No. I remember researches in 2020 claiming SARS-Cov-2 mutating slowly and a vaccine only will cover everything.

[It was evolving relatively slowly. Part of the reason for this is because, unlike many other RNA viruses, the coronaviruses have a proof-reading mechanism that helps to reduce the number of mutations they pick up.](https://royalsociety.org/blog/2021/03/how-is-covid-19-evolving/)

https://hub.jhu.edu/2020/06/10/sars-cov-2-dna-suggests-single-vaccine-will-be-effective/

**Comment by abergi** [comment] 2024-06-07 19:35
that's interesting. So actually no one, has ever thought that omicron would appear, and make things less severe. (?) which that's why i hear that with the common cold but still I don't know how possible that is but I guess it's the same with omicron too - how possible was that to happen. 

"My prediction is that as levels of immunity increase – both from natural infection and vaccination – the virus will eventually become [globally endemic](https://science.sciencemag.org/content/370/6516/527). It will continue circulating in populations, causing periodic outbreaks much like [the four seasonal coronaviruses](https://academic.oup.com/jid/article/222/7/1090/5874220) that are already endemic in humans"

She actually says it will be similar to other seasonal coronaviruses.

**Comment by aviczhl2** [comment] 2024-06-08 01:09
> She actually says it will be similar to other seasonal coronaviruses.

There were people trying to promote this opinion since 2020, despite their proof and logic are rapidly changing.

**Comment by aviczhl2** [comment] 2024-06-08 02:45
@abergi
I just see an online comment "Both of my parents die of their most recent SARS-2 infection in 2024.5, despite the virus has become much milder, it is still a danger".

Both of his parents die in a short period, and he still thinks the virus has become much milder. 
I feel suspective on personal sensitivity now. Do most people really have it? Is the mildness perspective unchallengeable?

**Comment by abergi** [comment] 2024-06-08 13:51
Did they have comorbidities  if you know? why they didn't use paxlovid?

Of course virus is still killing way more people than flu does. That's why I take precautions even though no one does around me, including my family. Not to mention that they make fun of me - everyone around.

**Comment by FedeGueli** [comment] 2024-06-08 15:19
It is not and very likely won't be a common cold virus ate least in the next years. that is just propaganda .

**Comment by abergi** [comment] 2024-06-08 15:34
I know. I just don't understand why WHO and other organizations dropped the testing and all the measures.
Do you think it can revert back to it's strains we had in 2020-2021?

**Comment by FedeGueli** [comment] 2024-06-08 17:15
> I know. I just don't understand why WHO and other organizations dropped the testing requirements and all the measures. Do you think it can revert back to it's strains we had in 2020-2021?

to me it is unlikely.

**Comment by aviczhl2** [comment] 2024-06-09 01:30
> It is not and very likely won't be a common cold virus ate least in the next years. that is just propaganda .

For people before SARS-2. yes. As we know how "cold" looks like and the difference between "common cold" and SARS-2.
  
For future generations, their cold-like disease may be mainly caused by SARS-2 due to its high infection rate and frequency, and their infections of "original common cold" may be minimal compared with their SARS-2 infection, so their understandings of "common cold" will be different from existing genrations. 

They may take "Cold is severe and will cause extreme damage." as theirbelief as most "cold" they experience are SARS-2 infections.

**Comment by abergi** [comment] 2024-10-25 10:18
Hi there, I am sorry to bother again.

I would like to ask, how do you see the evolution of the virus? Do the variants get weaker or stronger?
I've been reading multiple reports, and I am curious. Also on reddit https://www.reddit.com/r/COVID19positive/
I've been reading people's experiences with probably mainly KP.3.1.1 variant. Why the last year's variants were milder, and this one isn't so much? Last year - lost of taste and smell was uncommon, but now seems much common. Also there are studies suggesting that this might be because of virus infecting the brain. https://www.nature.com/articles/s41598-024-69772-y

Moreover now, I've been reading about XEC variant that could cause pneumonia - they say.. and that it combines two genomes. Does that make it much stronger?
https://www.medicoverhospitals.in/articles/new-covid-xec-strain-symptoms

What is valid?

**Comment by xz-keg** [comment] 2024-10-25 14:19
> @FedeGueli @xz-keg Hi there, I am sorry to bother again.
> 
> I would like to ask, how do you see the evolution of the virus? Do the variants get weaker or stronger? I've been reading multiple reports, and I am curious. Also on reddit https://www.reddit.com/r/COVID19positive/ I've been reading people's experiences with probably mainly KP.3.1.1 variant. Why the last year's variants were milder, and this one isn't so much? Last year - lost of taste and smell was uncommon, but now seems much common. Also there are studies suggesting that this might be because of virus infecting the brain. https://www.nature.com/articles/s41598-024-69772-y
> 
> Moreover now, I've been reading about XEC variant that could cause pneumonia - they say.. and that it combines two genomes. Does that make it much stronger? https://www.medicoverhospitals.in/articles/new-covid-xec-strain-symptoms
> 
> What is valid?

without sufficient clinical data nothing can be concluded. 

Given XEC hasn't reached dominant in any countries, I highly suspect those "XEC symptoms" are not really XEC cases. Unless there's sufficient variant-based clinical data we can have evidence of anything.
