### ISSUE TITLE
JN.1/FL.15* Recombinant (18 seq, Jan 7)

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#1269] opened 2024-01-07 22:44 UTC
### **Description**
**Recombinant of:** JN.1 (+ ORF1a:T170I) and FL.15*
**Earliest sequence:** 2023-11-7, USA, California — EPI_ISL_18623642
**Most recent sequence:** 2023-12-29, USA, New York — EPI_ISL_18724826
**Continents circulating:** North America (18)
**Countries circulating:** USA (16), Canada (2)
**Number of Sequences:** 18
**GISAID Nucleotide Query:** T28297C, C897A, C28846T, G27915T, C774T
**CovSpectrum Query:** [5-of: T28297C, C897A, C28846T, G27915T, C774T]
**Breakpoint:** Between 26833-27809

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons2/main/JN.1_FL.15_REcomb.json?c=gt-nuc_28846&gmax=29847&gmin=27847&label=id:node_6817972
<img width="1473" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/afbeb599-81df-4c70-b56b-e0549e034c33">

**Evidence**
I'm almost certain this must've been described somewhere here, but I can't find an issue on it and a search for C28846T doesn't return anything relevant. So I'm putting this out there. C28846T is the key mutation that reveals this to be a JN.1 recombinant with FL.15*. It's also distinguished from the nearby sequences on the Usher tree by having C774T (ORF1:T170I) and T18453C, which the  surrounding sequences lack.

This retains C26833T (M:A104V) but loses ORF7b:F19L (T27810C), so the one breakpoint has to be somewhere between 26833-27809, which seems to me like the ideal location for an JN.1/XBB breakpoint. I don't think there's anything in between there that is capable of distinguishing between FL.15* and JN.1.

There's one additional sequence from California that might belong in this branch—EPI_ISL_18621270. But it got the 5' end of an XBB up through at least 774 (ORF1a:170), though it still has C897A (ORF1a:A211D), so the 2nd breakpoint in that one has to be between 774-896. I'm guessing that one is a separate JN.1/FL.15* recombinant, but it could also be a sequence in this lineage that recombined again & got the first 800 or so nucleotides from an XBB of some sort. The addition of ORF1a:K47R and loss of ORF1a:T170I are the only things that distinguish it from the other sequences here. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_18604137, EPI_ISL_18614755, EPI_ISL_18623642,
EPI_ISL_18681730, EPI_ISL_18692017, EPI_ISL_18692065,
EPI_ISL_18692145, EPI_ISL_18710501, EPI_ISL_18710511,
EPI_ISL_18716141, EPI_ISL_18722339, EPI_ISL_18722342,
EPI_ISL_18724783, EPI_ISL_18724809, EPI_ISL_18724826,
EPI_ISL_18724864, EPI_ISL_18724880, EPI_ISL_18724892
</details>

**Comment by FedeGueli** [comment] 2024-01-07 23:36
Thank you Ryan i think this is a duplicate of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1177

**Comment by FedeGueli** [comment] 2024-01-07 23:38
Yes it is . Thank you for spotting closing this now. I ll keep your query to add to other issue too!

**Closed by FedeGueli** 2024-01-07 23:38 UTC
Labels: recombinant, Rapid review needed, duplicate, JN.1 Spike
