### ISSUE TITLE
KP.2.3(with 31del)+S:T572I FULLQUAD(49 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1781] opened 2024-07-25 07:21 UTC
Besides #1735, There is also a large KP.2.3+S:T572I emerged from a with 31del branch. (and many other small ones)

KP.2.3+S:S31del+C28714T+C23277T(S:T572I)

GISAID query:C28714T, C23277T, G25593T,G17334T,-9286,-24418, -C7851T,-C20233T,-C1267T
No. of seqs: 49(Canada 2 Denmark 2 Germany 3 Mauritius 1 Netherlands 2 Norway 3 Singapore 1 Spain 1 Sweden 18 USA 16(1 from France 1 from Germany))

First: EPI_ISL_19170222, Mauritius, 2024-4-24
Latest: EPI_ISL_19279801, USA from Germany, 2024-7-12

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice148_genome_test_1bceb_1b5000.json?label=id:node_5488669)
![image](https://github.com/user-attachments/assets/93732d50-5f75-4df8-958e-e317d6050e41)

**Comment by FedeGueli** [comment] 2024-07-25 07:38
Thx for spotting it is a duplicate of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1582 (that you contributed to with the query! )

**Closed by FedeGueli** 2024-07-25 07:38 UTC
Labels: FULL QUAD

**Comment by aviczhl2** [comment] 2024-07-25 08:48
> Thx for spotting it is a duplicate of #1582 (that you contributed to with the query! )

Please use the new query. I've add many -s to exclude separate emergences.

**Comment by FedeGueli** [comment] 2024-07-25 12:08
done
